site_name: 百度马蹄集周赛 2025
site_url: https://finger-bone.github.io/baidu-matiji-weekly-contest-2025/
site_description: 百度马蹄集周赛 2025

theme:
  name: lux
  font:
    text: Inter
    code: Fira Code

docs_dir: notes

nav:
- 第9次:
  - 二维二进制数: 09/03.md
  - 社团活动: 09/04.md
  - 神奇的树: 09/05.md

extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  mdx_math:
    enable_dollar_delimiter: true
